from typing import List, Tuple
from src.util.orchestration.loop_types import LoopAgent, LoopContext, LoopOutputModel, HistoryEntry
from src.pipeline.stage2.mapper.conceptual_model import ConceptualModel

class ConceptualFilterReport(LoopOutputModel):
    is_valid: bool = True
    det_errors: List[str] = []

    def get_errors(self) -> list[str]:
        return self.det_errors

class ConceptualFilterLoopAgent(LoopAgent):
    """
    Deterministic structural filter for the ER generation loop.
    Checks the ConceptualModel for hard structural errors and tracks soft warnings
    for suspiciously named foreign key attributes.
    """
    def __init__(self):
        self._warning_counts = {}
        self._last_model = None

    async def invoke(self, query: str) -> Tuple[LoopOutputModel, int]:
        report = ConceptualFilterReport()
        if not isinstance(self._last_model, ConceptualModel):
            report.is_valid = False
            report.det_errors.append("Model is missing or invalid.")
            return report, 0

        # Hard structural errors
        errors = self._last_model.get_errors()
        if errors:
            report.is_valid = False
            report.det_errors.extend(errors)

        # Soft warning tracker
        threshold = 2
        suspicious_attributes = self._check_suspicious_attributes()

        if suspicious_attributes:
            report.is_valid = False
            msg = (
                "The following attributes look like foreign keys or external references:\n" +
                "\n".join([f"- {attr}" for attr in suspicious_attributes]) +
                "\n\nI potentially flag these as not required because foreign keys will be automatically "
                "generated by the relational mapper later. Do you think you still need these in the ER? "
                "If not then take corrective measures (remove them). Otherwise, if you keep them, I will assume it is intentional."
            )
            report.det_errors.append(msg)

        return report, 0

    def build_context(self, ctx: LoopContext) -> str:
        self._last_model = ctx.node_outputs.get("extractor")
        return ""

    def _check_suspicious_attributes(self) -> List[str]:
        threshold = 2
        suspicious_attributes = []
        
        for e in self._last_model.entities:
            for a in e.attributes:
                a_low = a.name.lower()
                # Exclude primary keys
                if a_low in [pk.lower() for pk in e.identifier_attributes]:
                    continue
                
                is_suspicious = False
                # Heuristic 1: Common FK suffixes and prefixes
                if any(a_low.endswith(s) for s in ["_id", "_number", "_code", "_ref", "_key"]):
                    is_suspicious = True
                elif any(a_low.startswith(p) for p in ["fk_", "ref_"]):
                    is_suspicious = True
                else:
                    # Heuristic 2: Contains another entity's name (case insensitive)
                    # Heuristic 3: Matches another entity's PK name exactly
                    for other_e in self._last_model.entities:
                        if other_e.name.lower() == e.name.lower():
                            continue
                        
                        if other_e.name.lower() in a_low:
                            is_suspicious = True
                            break
                        
                        if a_low in [pk.lower() for pk in other_e.identifier_attributes]:
                            is_suspicious = True
                            break

                if is_suspicious:
                    key = (e.name, a.name)
                    self._warning_counts[key] = self._warning_counts.get(key, 0) + 1
                    
                    if self._warning_counts[key] <= threshold:
                        suspicious_attributes.append(f"Entity '{e.name}': '{a.name}'")
                        
        return suspicious_attributes

    def emit_history(self, output: LoopOutputModel, prior: LoopOutputModel | None, round_num: int, node: str) -> HistoryEntry:
        assert isinstance(output, ConceptualFilterReport)
        return HistoryEntry(
            round=round_num, 
            node=node, 
            changes_summary="Valid" if output.is_valid else f"Found {len(output.det_errors)} structural issues"
        )
