from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Union, Any, Dict, Set, Tuple
from .base import TableNode, BaseTableNode, RelationalCycleError

class ColumnNode(BaseModel):
    name: str = Field(description="Column name identifier.")

class ConstNode(BaseModel):
    value: Any = Field(description="Literal value node.")

class LogicalNode(BaseModel):
    """An atomic logical comparator."""
    operator: str = Field(description="Operator (GT, LT, EQUALS, etc.)")
    table: TableNode
    column_1: Union[ColumnNode, ConstNode]
    column_2: Union[ColumnNode, ConstNode]

    def describe(self) -> str: return f"Comparison"
    def get_signature(self, schema: Any) -> str:
        c1_s = f"Col:{self.column_1.name.upper()}" if isinstance(self.column_1, ColumnNode) else f"Const:{self.column_1.value}"
        c2_s = f"Col:{self.column_2.name.upper()}" if isinstance(self.column_2, ColumnNode) else f"Const:{self.column_2.value}"
        return f"Logical:{self.table.get_signature(schema)}:{c1_s}:{self.operator}:{c2_s}"

    def unify(self, reg: Dict[str, Any], schema: Any, path: Optional[List[Any]] = None) -> 'LogicalNode':
        if path is None: path = []
        path.append(self); self.table = self.table.unify(reg, schema, path); path.pop()
        sig = self.get_signature(schema)
        if sig in reg: return reg[sig]
        reg[sig] = self; return self
    def _validate(self, schema: Any) -> List[str]:
        errors = self.table._validate(schema)
        # Type mismatch check
        type1 = self.column_1.name if isinstance(self.column_1, ColumnNode) else "CONST"
        type2 = self.column_2.name if isinstance(self.column_2, ColumnNode) else "CONST"

        def get_type(node: Union[ColumnNode, ConstNode], table: TableNode, schema: Any) -> Optional[str]:
            if isinstance(node, ColumnNode):
                if not hasattr(table, 'get_column_type'): return None
                return table.get_column_type(node.name, schema)
            else: # ConstNode
                v = node.value
                if isinstance(v, bool): return "BOOLEAN"
                if isinstance(v, int): return "INTEGER"
                if isinstance(v, float): return "FLOAT"
                if isinstance(v, str): return "VARCHAR"
                return None

        t1 = get_type(self.column_1, self.table, schema)
        t2 = get_type(self.column_2, self.table, schema)

        if t1 and t2:
            # Normalize for comparison
            # Handle types like DECIMAL(4,2) or VARCHAR(255)
            u1 = t1.upper().split("(")[0].strip()
            u2 = t2.upper().split("(")[0].strip()
            numeric = {"INT", "INTEGER", "FLOAT", "DECIMAL", "NUMERIC", "DOUBLE", "REAL", "BIGINT", "SMALLINT", "TINYINT"}
            if u1 != u2:
                # If one is numeric and the other is too, it's generally fine.
                if u1 in numeric and u2 in numeric:
                    pass
                else:
                    col1_desc = f"Column '{self.column_1.name}'" if isinstance(self.column_1, ColumnNode) else f"Constant '{self.column_1.value}'"
                    col2_desc = f"Column '{self.column_2.name}'" if isinstance(self.column_2, ColumnNode) else f"Constant '{self.column_2.value}'"
                    errors.append(f"Type mismatch in logic '{self.operator}': {col1_desc} ({t1}) and {col2_desc} ({t2}) must have matching data types in table {self.table.describe()}.")

        return errors

class CombinationNode(BaseModel):
    """Combines multiple logic nodes with AND/OR."""
    operator: str = Field(description="Logical operator (AND, OR)")
    operands: List[Union[LogicalNode, 'CombinationNode']]
    table: TableNode

    def describe(self) -> str: return f"Compound"
    def get_signature(self, s: Any) -> str:
        return f"Comb:{self.operator}:[{'|'.join(sorted([o.get_signature(s) for o in self.operands]))}]"

    def unify(self, reg: Dict[str, Any], s: Any, path: Optional[List[Any]]= None) -> 'CombinationNode':
        if path is None: path = []
        path.append(self); self.table = self.table.unify(reg, s, path)
        self.operands = [op.unify(reg, s, path) for op in self.operands]; path.pop()
        sig = self.get_signature(s)
        if sig in reg: return reg[sig]
        reg[sig] = self; return self
    def _validate(self, s: Any) -> List[str]:
        errs = self.table._validate(s)
        for o in self.operands: errs.extend(o._validate(s))
        return errs

class JoinNode(BaseModel):
    """A virtual table generated by a JOIN."""
    name: str = Field(description="Unique name for this join view.")
    l_table: TableNode
    l_column: 'ColumnNode'
    r_table: TableNode
    r_column: 'ColumnNode'

    def get_backbone_side(self, schema: Any) -> TableNode:
        orig_l_sig = self.l_table.find_origin_table(self.l_column.name, schema)
        orig_r_sig = self.r_table.find_origin_table(self.r_column.name, schema)
        orig_l = orig_l_sig.split(":")[1] if ":" in orig_l_sig else orig_l_sig
        orig_r = orig_r_sig.split(":")[1] if ":" in orig_r_sig else orig_r_sig
        r_to_l = False
        if hasattr(schema, 'relationships') and schema.relationships:
            for rel in schema.relationships:
                if (rel.referencing_table.upper() == orig_r.upper() and rel.referencing_column.upper() == self.r_column.name.upper() and rel.referred_table.upper() == orig_l.upper()):
                    r_to_l = True; break
        l_to_r = False
        if hasattr(schema, 'relationships') and schema.relationships:
            for rel in schema.relationships:
                if (rel.referencing_table.upper() == orig_l.upper() and rel.referencing_column.upper() == self.l_column.name.upper() and rel.referred_table.upper() == orig_r.upper()):
                    l_to_r = True; break
        return self.r_table if r_to_l else (self.l_table if l_to_r else self.l_table)

    def get_identity_col(self, schema: Any) -> str:
        return self.get_backbone_side(schema).get_identity_col(schema)

    def get_columns(self, schema: Any) -> Set[str]:
        l_cols = self.l_table.get_columns(schema)
        r_cols = self.r_table.get_columns(schema)
        final_cols = {self.l_column.name}
        final_cols.update(l_cols)
        final_cols.update(r_cols)
        return final_cols

    def describe(self) -> str: return f"Join '{self.name}'"
    def get_signature(self, schema: Any) -> str:
        tabs, preds = self.get_relational_components(schema)
        return f"FlatJoin:[{','.join(sorted(tabs))}]:[{','.join(sorted(preds))}]"

    def get_relational_components(self, schema: Any) -> 'Tuple[Set[str], Set[str]]':
        l_t, l_p = self.l_table.get_relational_components(schema); r_t, r_p = self.r_table.get_relational_components(schema)
        p1 = f"{self.l_table.find_origin_table(self.l_column.name, schema)}.{self.l_column.name.upper()}"
        p2 = f"{self.r_table.find_origin_table(self.r_column.name, schema)}.{self.r_column.name.upper()}"
        curr = f"{min(p1, p2)}=={max(p1, p2)}"
        return l_t | r_t, l_p | r_p | {curr}

    def find_origin_table(self, column_name: str, schema: Any) -> str:
        if column_name in self.l_table.get_columns(schema): return self.l_table.find_origin_table(column_name, schema)
        return self.r_table.find_origin_table(column_name, schema)

    def unify(self, reg: Dict[str, Any], schema: Any, path: Optional[List[Any]] = None) -> 'JoinNode':
        if path is None: path = []
        path.append(self); self.l_table = self.l_table.unify(reg, schema, path); self.r_table = self.r_table.unify(reg, schema, path); path.pop()
        sig = self.get_signature(schema)
        if sig in reg: return reg[sig]
        reg[sig] = self; return self
    def get_column_type(self, column_name: str, schema: Any) -> Optional[str]:
        if column_name in self.l_table.get_columns(schema): return self.l_table.get_column_type(column_name, schema)
        if column_name in self.r_table.get_columns(schema): return self.r_table.get_column_type(column_name, schema)
        return None

    def _validate(self, schema: Any) -> List[str]:
        errors = self.l_table._validate(schema) + self.r_table._validate(schema)

        l_type = self.l_table.get_column_type(self.l_column.name, schema)
        r_type = self.r_table.get_column_type(self.r_column.name, schema)

        if l_type and r_type:
            # Handle types like DECIMAL(4,2) or VARCHAR(255)
            u1 = l_type.upper().split("(")[0].strip()
            u2 = r_type.upper().split("(")[0].strip()
            numeric = {"INT", "INTEGER", "FLOAT", "DECIMAL", "NUMERIC", "DOUBLE", "REAL", "BIGINT", "SMALLINT", "TINYINT"}
            if u1 != u2:
                if not (u1 in numeric and u2 in numeric):
                    errors.append(f"Join type mismatch in '{self.name}': {self.l_table.describe()}.{self.l_column.name} ({l_type}) must match {self.r_table.describe()}.{self.r_column.name} ({r_type}).")

        return errors

class AggNode(BaseModel):
    """A virtual table generated by an AGGREGATION."""
    name: str = Field(description="Unique name for the aggregation result.")
    source_table: TableNode
    group_by_column: 'ColumnNode'
    aggregate_column: 'ColumnNode'
    operator: str = Field(description="AGGREGATE operator (SUM, AVG, etc.)")
    extra_exposed_columns: List[str] = Field(default_factory=list)

    def get_identity_col(self, schema: Any) -> str:
        return self.group_by_column.name

    def describe(self) -> str: return f"Agg '{self.name}' ({self.operator})"
    def get_columns(self, schema: Any) -> Set[str]:
        cols = {self.group_by_column.name, f"{self.operator.lower()}_{self.aggregate_column.name}"}
        cols.update(self.extra_exposed_columns)
        return cols

    def get_signature(self, schema: Any) -> str:
        return f"Agg:{self.source_table.get_signature(schema)}:{self.group_by_column.name.upper()}+{self.aggregate_column.name.upper()}:{self.operator}"

    def get_relational_components(self, schema: Any) -> 'Tuple[Set[str], Set[str]]': return {self.get_signature(schema)}, set()
    def find_origin_table(self, column_name: str, schema: Any) -> str: return self.get_signature(schema)

    def unify(self, reg: Dict[str, Any], schema: Any, path: Optional[List[Any]] = None) -> 'AggNode':
        if path is None: path = []
        path.append(self); self.source_table = self.source_table.unify(reg, schema, path); path.pop()
        sig = self.get_signature(schema)
        if sig in reg: return reg[sig]
        reg[sig] = self; return self
    def get_column_type(self, column_name: str, schema: Any) -> Optional[str]:
        if column_name == self.group_by_column.name: return self.source_table.get_column_type(column_name, schema)
        if column_name == f"{self.operator.lower()}_{self.aggregate_column.name}":
            # Heuristic: Aggregate is usually numeric
            return "FLOAT"
        return self.source_table.get_column_type(column_name, schema)

    def _validate(self, schema: Any) -> List[str]: return self.source_table._validate(schema)

class ConditionPair(BaseModel):
    condition: Union[LogicalNode, CombinationNode] = Field(description="The IF predicate.")
    result: Union[LogicalNode, CombinationNode] = Field(description="The THEN outcome.")
    def get_signature(self, s: Any) -> str: return f"P:{self.condition.get_signature(s)}->{self.result.get_signature(s)}"
    def unify(self, reg: Dict[str, Any], s: Any, path: Optional[List[Any]] = None) -> 'ConditionPair':
        if path is None: path = []
        path.append(self); self.condition = self.condition.unify(reg, s, path); self.result = self.result.unify(reg, s, path); path.pop()
        sig = self.get_signature(s)
        if sig in reg: return reg[sig]
        reg[sig] = self; return self

class IfNode(BaseModel):
    """An IF node anchored to a specific base table."""
    anchor_table: TableNode
    on: str = Field(default="", description="The SQL relational scope (JOIN/SELECT) where this rule applies.")
    pairs: List[ConditionPair] = Field(description="Sequence of IF-THEN pairs.")
    fact_references: List[int] = Field(default_factory=list, description="IDs of the facts supporting this logical rule.")

    @field_validator('fact_references')
    @classmethod
    def must_have_facts(cls, v: List[int]) -> List[int]:
        if not v:
            raise ValueError("All logical rules (IfNodes) must have at least one supporting fact_reference.")
        return v

    def describe(self) -> str: return f"IfChain"
    def get_signature(self, s: Any) -> str:
        return f"If:{self.anchor_table.get_signature(s)}:[{'|'.join([p.get_signature(s) for p in self.pairs])}]"

    def unify(self, reg: Dict[str, Any], s: Any, path: Optional[List[Any]] = None) -> 'IfNode':
        if path is None: path = []
        path.append(self); self.anchor_table = self.anchor_table.unify(reg, s, path)
        self.pairs = [p.unify(reg, s, path) for p in self.pairs]; path.pop()
        sig = self.get_signature(s)
        if sig in reg: return reg[sig]
        reg[sig] = self; return self
    def _validate(self, s: Any) -> List[str]:
        errs = self.anchor_table._validate(s)
        for p in self.pairs:
            errs.extend(p.condition._validate(s))
            errs.extend(p.result._validate(s))
        return errs
